obstacle_range: 2.0
raytrace_range: 2.5
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [[0.30, 0.35], [-0.30, 0.35], [-0.30, -0.35], [0.30, -0.35]]
#robot_radius: 0.45
inflation_radius: 0.35
# observation_sources: scan_name cloud_name
observation_sources: base_scan
# scan_name: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
# cloud_name: {sensor_frame: frame_name, data_type: PointCloud2, topic: topic_name, marking: true, clearing: true}
base_scan: {
  sensor_frame: lrf_link,
  data_type: LaserScan,
  topic: /scan,
  marking: true,
  clearing: true, #default is false because It take some lisks
  max_obstacle_height: 1.0,
  min_obstacle_height: -0.15,
  expected_update_rate: 1.0,
  observation_persistence: 0.0
}